name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Build
      run: cargo build --release
    
    - name: Create Debian package
      run: |
        cargo install cargo-deb
        cargo deb
    
    - name: Upload Linux binary
      uses: actions/upload-artifact@v3
      with:
        name: autosetup-linux
        path: target/release/autosetup
    
    - name: Upload Debian package
      uses: actions/upload-artifact@v3
      with:
        name: autosetup-deb
        path: target/debian/*.deb

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Build
      run: cargo build --release
    
    - name: Upload macOS binary
      uses: actions/upload-artifact@v3
      with:
        name: autosetup-macos
        path: target/release/autosetup

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Build
      run: cargo build --release
    
    - name: Upload Windows binary
      uses: actions/upload-artifact@v3
      with:
        name: autosetup-windows
        path: target/release/autosetup.exe

  release:
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Download artifacts
      uses: actions/download-artifact@v3
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          autosetup-linux/autosetup
          autosetup-macos/autosetup
          autosetup-windows/autosetup.exe
          autosetup-deb/*.deb
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-crates:
    needs: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Publish to crates.io
      run: cargo publish --token ${{ secrets.CRATES_TOKEN }}

  update-homebrew:
    needs: release
    runs-on: ubuntu-latest
    steps:
    - name: Update Homebrew formula
      run: |
        echo "TODO: Update homebrew-tap repository with new version"